#!/bin/bash

clear
make

cd Example
llvm-gcc -O0 -emit-llvm -c loop.c -o obj.o

llvm-dis obj.o

opt -load ~/Programs/llvm/Debug/lib/DSWP.so -dswp obj.o -o out.o

llvm-dis out.o

#cat showgraph
#cat dag
#cat partition

cd ..
