#!/bin/bash

clear
make

cd Example
llvm-gcc -O0 -emit-llvm -c simple.c

llvm-dis simple.o

opt -load ~/Programs/llvm/Debug/lib/DSWP.so -dswp simple.o -o out.o

llvm-dis out.o

#cat showgraph
#cat dag
#cat partition

cd ..
